version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  kafka:
    image: confluentinc/cp-kafka:latest
    # ... (configurações do Kafka) ...

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    depends_on:
      - mongodb
      - kafka

  api-test:
    build:
      context: .
      dockerfile: API/Dockerfile
      target: development
    depends_on:
      - mongodb
      - kafka

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - kafka

  worker-test:
    build:
      context: .
      dockerfile: worker/Dockerfile
      target: development
    depends_on:
      - kafka